# Generated by Django 6.1 on 2026-08-19 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('walking', 'Walking')], max_length=30)),
                ('activity_date', models.DateField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('avg_pace_min_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('elevation_gain_m', models.IntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
