# Generated by Django 6.1 on 2026-08-14 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight loss'), ('muscle_gain', 'Muscle gain'), ('strength', 'Strength'), ('running', 'Running'), ('cycling', 'Cycling'), ('general_fitness', 'General fitness')], max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
    ]
